In [1]:
import numpy as np

In [3]:
array_np = np.array([1,2,3])
print("this is 1d numpy array", array_np)

this is 1d numpy array [1 2 3]


In [5]:
array_2d = np.array([[1,2,3],[2,4,6]])
print("this is 2d numpy array", array_2d)

this is 2d numpy array [[1 2 3]
 [2 4 6]]


In [7]:
#multiplication
array_2d = np.array([[1,2,3],[2,4,6]])
print("this is 2d numpy array", array_2d *2)

this is 2d numpy array [[ 2  4  6]
 [ 4  8 12]]


In [11]:
#diffrence between list multiplication and numpy multiplication

listex = [2,3,5]
print("This is list multiplication", listex *3)

array_2d = np.array([[1,2,3],[2,4,6]])
print("this is 2d numpy array", array_2d *5)

This is list multiplication [2, 3, 5, 2, 3, 5, 2, 3, 5]
this is 2d numpy array [[ 5 10 15]
 [10 20 30]]


In [15]:
#calculating time for list and numpy array

import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("This is time for the list", time.time() - start)

This is time for the list 0.0748758316040039


In [17]:
import time
start = time.time()
py_array = np.arange(10000000)*2
print("This is time for the numpy operation", time.time() - start)

This is time for the numpy operation 0.03117513656616211


In [63]:
#now vectors. matrices, tensor

#vector

vector = np.array([1,2,4])
print("This is vector: ", vector)

#mtrix
matrices = np.array([[1,5,9] ,
                     [2,9,1]])
print("This is matrices: ", matrices)

#tensors
#tenosor = [[[[1,5,9] ,
  #       [2,9,1] ,
  #          [2,9,1)]]]
#print("This is tensor: ", tensor)


This is vector:  [1 2 4]
This is matrices:  [[1 5 9]
 [2 9 1]]


In [65]:
## array properties

matrices = np.array([[1,5,9] ,
                     [2,9,1]])
print("shape : ", matrices.shape)

shape :  (2, 3)


In [67]:
matrices = np.array([[1,5,9] ,
                     [2,9,1]])
print("dimension of this arr is : ", matrices.ndim)

dimension of this arr is :  2


In [69]:
#reshaping an array
matrices = np.array([[1,5,9] ,
                     [2,9,1]])
print("reshaped of this arr is : ", matrices.reshape((3,2)))


reshaped of this arr is :  [[1 5]
 [9 2]
 [9 1]]


In [71]:
#reshaping an array
matrices = np.array([[1,5,9] ,
                     [2,9,1]])
print("flttened of this arr is : ", matrices.flatten())


falttened of this arr is :  [1 5 9 2 9 1]


In [73]:
#transpore

matrices = np.array([[1,5,9] ,
                     [2,9,1]])
print("flttened of this arr is : ", matrices.T)

flttened of this arr is :  [[1 2]
 [5 9]
 [9 1]]


In [75]:
#PHASE 2 OF NUMPY

In [79]:
#sorting in numpy 1d array

matrices = np.array([1,5,9.20, 50, 60,110])
print("sorted array is here", np.sort(matrices))

sorted array is here [  1.    5.    9.2  50.   60.  110. ]


In [99]:
#sorting in numpy 2d array
matrices = np.array([[1,5,9] ,
                     [2,9,1],
                     [3,2,6]])
print("This is sorted 2d array: ", np.sort(matrices, axis=0))

This is sorted 2d array:  [[1 2 1]
 [2 5 6]
 [3 9 9]]


In [105]:
#filtering in numpy
arr = np.array([[1,2,3,4,5,6,7,8,9,10]])
print(arr)

#filtering with mask
mask = arr >5
print("This is done with filtering with mask: ", arr[mask])

#normal filering
evenno = arr[arr %2==0]
print("This is done with filtering with mask: ", evenno)

[[ 1  2  3  4  5  6  7  8  9 10]]
This is done with filtering with mask:  [ 6  7  8  9 10]
This is done with filtering with mask:  [ 2  4  6  8 10]


In [117]:
#where in numpy 

conditionalcheck = np.where(arr >5)
print("This is done with where: ", arr[conditionalcheck])


This is done with where:  [ 6  7  8  9 10]


In [119]:
#This is done using another if else like where function
conditionalcheck = np.where(arr>5, arr*2, arr)
#the above part works like if else structure just like the sql one
#here is how it is working, arr>5 <-- this is conditional check like if (condition)
#arr*2 is like that if(){ arr*2) condition that will be exceute
#arr is the else else part of if-else statement

print("conditional check is: ", conditionalcheck)

conditional check is:  [[ 1  2  3  4  5 12 14 16 18 20]]


In [123]:
#combining two arrys using numpy

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combinedarray = np.concatenate((arr1,arr2))
print(combinedarray)

[1 2 3 4 5 6]


In [131]:
#gemini question 
#Create a 1D NumPy array containing all the integers from 10 to 29.

arr1 =np.array([10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29])
print(arr1)

#Reshape this array into a 4x5 matrix (4 rows, 5 columns).

reshapedarray = arr1.reshape(4,5)
print(reshapedarray)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [151]:
#From this 4x5 matrix, create a "mask" to find all values that are greater than 22.
masked = reshapedarray >22
print("this is after masked the values are this : ", masked)

mask = np.where(reshapedarray >22)
print("this is after masked the values are this : ",reshapedarray[masked])

sumis = np.sum(reshapedarray[masked], axis=0)
print(sumis)

this is after masked the values are this :  [[False False False False False]
 [False False False False False]
 [False False False  True  True]
 [ True  True  True  True  True]]
this is after masked the values are this :  [23 24 25 26 27 28 29]
182
